### ISSUE TITLE
Is the Jolt 0.1.6 version compatible with Java 11

### ISSUE THREAD

**Issue by gawhadebhavna** [bazaarvoice/jolt#1183]
Hi, 

Just want to know, is the Jolt 0.1.6 version compatible with Java 11?

I have faced the below issue when I'm trying to use the jolt libraries.
BUG! exception in phase 'semantic analysis' in source unit '............./lib/jolt-core-0.1.6.jar!/com/bazaarvoice/jolt/Chainr.class\n'

Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 24: jar:file:/............/jolt-core-0.1.6.jar!/com/bazaarvoice/jolt/Chainr.class
        at java.net.URI$Parser.fail(URI.java:2913) ~[?:?]
        at java.net.URI$Parser.checkChars(URI.java:3084) ~[?:?]
        at java.net.URI$Parser.parse(URI.java:3120) ~[?:?]
        at java.net.URI.<init>(URI.java:600) ~[?:?]
        at java.net.URL.toURI(URL.java:1061) ~[?:?]

**Comment by gawhadebhavna** [comment]
Yes, the Jolt 0.1.6 version is compatible with Java 11.
