### ISSUE TITLE
Adding json-utils to our POM causes all tests to fail.

### ISSUE THREAD

**Issue by qwelyt** [bazaarvoice/jolt#146]
For some reason, adding json-utils as a dependency breaks _all_ of our tests.
```
<dependency>
    <groupId>com.bazaarvoice.jolt</groupId>
    <artifactId>json-utils</artifactId>
    <version>0.0.16</version>
</dependency>
```
This is what we put in our pom.
And this is what it makes out tests put out: 
```
java.lang.NoClassDefFoundError: com/fasterxml/jackson/annotation/ObjectIdResolver
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:476)
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:391)
	at my.company.server.application.infrastructure.Deserializer.<init>(Deserializer.java:24)
	at my.company.server.application.infrastructure.DeserializerTest.setUp(DeserializerTest.java:74)
```

So, pointers an why json-utils does that would be greatful.
If it's any help, other deps we have are dropwizard, mysql, aspecj, icu4j, appache-commons, rabbitmq, jodah, junit, mockito, hamcrest, and jconch. We also use guava and jackson.

So, what in json-utils is it that makes all of this fail? Importing just `jolt-core` works great. But I see now guides for how to use jolt without json-utils. If you could put an example of that, it would be appreciated.

All help welcome.

**Comment by qwelyt** [comment]
Solved it with an exclusion of jackson from json-utils.
```
    <dependency>
            <groupId>com.bazaarvoice.jolt</groupId>
            <artifactId>json-utils</artifactId>
            <version>${jolt.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-core</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.fasterxml.jackson.core</groupId>
                    <artifactId>jackson-databind</artifactId>
                </exclusion>
            </exclusions>
    </dependency>
```

**Comment by milosimpson** [comment]
Yeah, you must be using a significantly different version of Jackson.
