### ISSUE TITLE
Issue trying to read spec from from classpath.

### ISSUE THREAD

**Issue by javadevmtl** [bazaarvoice/jolt#349]
Hi using 0.1.0

This throws an exception: JsonUtils.classpathToList("result-spec.json");

```
java.lang.RuntimeException: Unable to load JSON map from classPath : result-spec.json
	at com.bazaarvoice.jolt.JsonUtilImpl.classpathToList(JsonUtilImpl.java:225)
	at com.bazaarvoice.jolt.JsonUtils.classpathToList(JsonUtils.java:165)
```

This does not: JsonUtils.jsonToList(this.getClass().getClassLoader().getResourceAsStream("result-spec.json"));

Running IntelliJ and the file is in src/main/resources

Here is the print output of the classpath

```
/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/charsets.jar
/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/deploy.jar
/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/cldrdata.jar
/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/dnsns.jar
/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/jaccess.jar
/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/jfxrt.jar
/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/localedata.jar
/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/nashorn.jar
/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/sunec.jar
/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar
/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar
/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/zipfs.jar
/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/javaws.jar
/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/jce.jar
/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/jfr.jar
/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/jfxswt.jar
/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/jsse.jar
/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/management-agent.jar
/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/plugin.jar
/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/resources.jar
/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/rt.jar
/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/lib/ant-javafx.jar
/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/lib/dt.jar
/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/lib/javafx-mx.jar
/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/lib/jconsole.jar
/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/lib/packager.jar
/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/lib/sa-jdi.jar
/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/lib/tools.jar
/Users/me/Documents/IdeaProjects/event-platform-mapreduce/search-api/build/classes/main/
/Users/me/Documents/IdeaProjects/event-platform-mapreduce/search-api/build/resources/main/
/Users/me/.gradle/caches/modules-2/files-2.1/io.netty/netty-common/4.1.8.Final/ee62c80318413d2375d145e51e48d7d35c901324/netty-common-4.1.8.Final.jar
/Users/me/.gradle/caches/modules-2/files-2.1/com.bazaarvoice.jolt/json-utils/0.1.0/6c3b831f0d08775d8610b14f8c8ebaae88e3cd4/json-utils-0.1.0.jar
/Users/me/.gradle/caches/modules-2/files-2.1/io.netty/netty-buffer/4.1.8.Final/43292c2622e340a0d07178c341ca3bdf3d662034/netty-buffer-4.1.8.Final.jar
/Users/me/.gradle/caches/modules-2/files-2.1/io.netty/netty-transport/4.1.8.Final/905b5dadce881c9824b3039c0df36dabbb7b6a07/netty-transport-4.1.8.Final.jar
/Users/me/.gradle/caches/modules-2/files-2.1/io.netty/netty-handler/4.1.8.Final/db01139bfb11afd009a695eef55b43bbf22c4ef5/netty-handler-4.1.8.Final.jar
/Users/me/.gradle/caches/modules-2/files-2.1/io.netty/netty-handler-proxy/4.1.8.Final/c4d22e8b9071a0ea8d75766d869496c32648a758/netty-handler-proxy-4.1.8.Final.jar
/Users/me/.gradle/caches/modules-2/files-2.1/io.netty/netty-codec-http/4.1.8.Final/1e88617c4a6c88da7e86fdbbd9494d22a250c879/netty-codec-http-4.1.8.Final.jar
/Users/me/.gradle/caches/modules-2/files-2.1/io.netty/netty-codec-http2/4.1.8.Final/105a99ee5767463370ccc3d2e16800bd99f5648e/netty-codec-http2-4.1.8.Final.jar
/Users/me/.gradle/caches/modules-2/files-2.1/io.netty/netty-resolver/4.1.8.Final/2e116cdd5edc01b2305072b1dbbd17c0595dbfef/netty-resolver-4.1.8.Final.jar
/Users/me/.gradle/caches/modules-2/files-2.1/io.netty/netty-resolver-dns/4.1.8.Final/e2f8a3919ba592c22ddbf5484708ed02e099c90/netty-resolver-dns-4.1.8.Final.jar
/Users/me/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-core/2.7.4/b8f38a249116b66d804a5ca2b14a3459b7913a94/jackson-core-2.7.4.jar
/Users/me/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-databind/2.7.4/1e9c6f3659644aeac84872c3b62d8e363bf4c96d/jackson-databind-2.7.4.jar
/Users/me/.gradle/caches/modules-2/files-2.1/io.netty/netty-codec/4.1.8.Final/1bd0a2d032e5c7fc3f42c1b483d0f4c57eb516a3/netty-codec-4.1.8.Final.jar
/Users/me/.gradle/caches/modules-2/files-2.1/io.netty/netty-codec-socks/4.1.8.Final/7f7c5f5b154646d7c571f8ca944fb813f71b1d51/netty-codec-socks-4.1.8.Final.jar
/Users/me/.gradle/caches/modules-2/files-2.1/io.netty/netty-codec-dns/4.1.8.Final/dbce8c6486d635db2176889710d784597b5e4a1b/netty-codec-dns-4.1.8.Final.jar
/Users/me/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-annotations/2.7.0/19f42c154ffc689f40a77613bc32caeb17d744e3/jackson-annotations-2.7.0.jar
/Users/me/.gradle/caches/modules-2/files-2.1/org.apache.httpcomponents/httpclient/4.4.1/16d0bc512222f1253ee6b64d389c84e22f697f0/httpclient-4.4.1.jar
/Users/me/.gradle/caches/modules-2/files-2.1/org.apache.httpcomponents/httpcore/4.4.1/f5aa318bda4c6c8d688c9d00b90681dcd82ce636/httpcore-4.4.1.jar
/Users/me/.gradle/caches/modules-2/files-2.1/org.apache.httpcomponents/httpmime/4.4.1/2f8757f5ac5e38f46c794e5229d1f3c522e9b1df/httpmime-4.4.1.jar
/Users/me/.gradle/caches/modules-2/files-2.1/org.apache.zookeeper/zookeeper/3.4.6/1b2502e29da1ebaade2357cd1de35a855fa3755/zookeeper-3.4.6.jar
/Users/me/.gradle/caches/modules-2/files-2.1/org.codehaus.woodstox/stax2-api/3.1.4/ac19014b1e6a7c08aad07fe114af792676b685b7/stax2-api-3.1.4.jar
/Users/me/.gradle/caches/modules-2/files-2.1/org.codehaus.woodstox/woodstox-core-asl/4.4.1/84fee5eb1a4a1cefe65b6883c73b3fa83be3c1a1/woodstox-core-asl-4.4.1.jar
/Users/me/.gradle/caches/modules-2/files-2.1/org.noggit/noggit/0.6/fa94a59c44b39ee710f3c9451750119e432326c0/noggit-0.6.jar
/Users/me/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.7.7/2b8019b6249bb05d81d3a3094e468753e2b21311/slf4j-api-1.7.7.jar
/Users/me/.gradle/caches/modules-2/files-2.1/org.apache.solr/solr-solrj/6.4.2/2e92c434bd65d730bd188616b62e617c0581d91/solr-solrj-6.4.2.jar
/Users/me/.gradle/caches/modules-2/files-2.1/commons-io/commons-io/2.5/2852e6e05fbb95076fc091f6d1780f1f8fe35e0f/commons-io-2.5.jar
/Users/me/.gradle/caches/modules-2/files-2.1/org.slf4j/jcl-over-slf4j/1.7.7/56003dcd0a31deea6391b9e2ef2f2dc90b205a92/jcl-over-slf4j-1.7.7.jar
/Users/me/.gradle/caches/modules-2/files-2.1/io.vertx/vertx-core/3.4.1/ae1a5247efaa9f96bce91c5cf08681d615c709f9/vertx-core-3.4.1.jar
/Users/me/.gradle/caches/modules-2/files-2.1/io.vertx/vertx-web/3.4.1/8dfa76a2c939bb186261533c55edb496fc250060/vertx-web-3.4.1.jar
/Users/me/.gradle/caches/modules-2/files-2.1/io.vertx/vertx-auth-common/3.4.1/6fb7f8f86674560c4ddee46b0902aa0a69ce63ca/vertx-auth-common-3.4.1.jar
/Users/me/.gradle/caches/modules-2/files-2.1/com.bazaarvoice.jolt/jolt-core/0.1.0/df0dac4c9f2479e10e25bb8750c23531c80eee4b/jolt-core-0.1.0.jar
/Users/me/.gradle/caches/modules-2/files-2.1/javax.inject/javax.inject/1/6975da39a7040257bd51d21a231b76c915872d38/javax.inject-1.jar
/Applications/IntelliJ%20IDEA.app/Contents/lib/idea_rt.jar
```

**Comment by milosimpson** [comment]
Yep.

```
JsonUtils.classpathToList("result-spec.json");

This trys to load the file using the classLoader of the Jolt jar file, which may not have access to classpath things from "your" jar.

JsonUtils.jsonToList(this.getClass().getClassLoader().getResourceAsStream("result-spec.json"));

Means you are using the classLoader of "this", which is your code to try to load your spec file.
```

**Comment by javadevmtl** [comment]
Then thats kinda confusing as a function :)

**Comment by milosimpson** [comment]
That is Java class loaders for you.

The only thing Jolt could do is offer all the JsonUtils.classpath* methods that take a classLoader as a param, but that really clutters the interface.

**Comment by joseluisbsa** [comment]
Hi,

Can you help me? How do I know the Class path?
I'm with the same error.

**Comment by Minnull** [comment]
me too

**Comment by DanFServ** [comment]
> this.getClass().getClassLoader().getResourceAsStream("result-spec.json")

This did the trick for me, thank you very much.
