### ISSUE TITLE
Getting error JOLT Chainr could not find transform class modify-overwrite-beta

### ISSUE THREAD

**Issue by santooudnur** [bazaarvoice/jolt#413]
I am trying to programmatically transform JSON data  from spring boot application .Getting  JOLT Chainr could not find transform class:modify-overwrite-beta at index:1.

I am using cradle for dependencies
compile group: 'com.bazaarvoice.jolt', name: 'jolt-core', version: '0.0.20
compile group: 'com.bazaarvoice.jolt', name: 'json-utils', version: '0.0.20'

JSON Spec 
```
[
	{
		"operation": "shift",
		"spec": {
			"file-info": {
				"filename": "filename"
			},
			"main-text": {
				"*": {
					"text": "document"
				}
			},
			"tables": {
				"*": {
					"data": "data&1"
				}
			},
			"\\*": "\\&1.&"
		}
	},
	{
		"operation": "modify-overwrite-beta",
		"spec": {
			"document": "=join('',@(1,document))",
			"data*": {
				"*": "=join('',@(2,&1[&]))"
			}
		}
	},
	{
		
		"operation": "modify-overwrite-beta",
		"spec": {
			"data*": "=join(' ',@(1,&))"
		}
	}
]
```

The above code tested for input JSON on web interface at http://jolt-demo.appspot.com/#inception
The spec is loaded
Here is java code
```
public  String transformJSON(String inputJSON) {
		logger.info("[JSONTransformationUtility] /transformJSON start : ");

		try {
			System.out.println(inputJSON);
			
			
			Object inputJSON1 = JsonUtils.jsonToObject(inputJSON);
				
			
			System.out.println(inputJSON1.toString());
			System.out.println(getStringFromInputStream(this.getClass().getClassLoader().getResourceAsStream(DEFAULT_JSON_TRANFORM_SPEC)));
			List<Object> chainrSpecJSON =JsonUtils.jsonToList(this.getClass().getClassLoader().getResourceAsStream(DEFAULT_JSON_TRANFORM_SPEC));

			Chainr chainr = Chainr.fromSpec(chainrSpecJSON);


			// Object inputJSON = JsonUtils.classpathToObject( "/json/sample/input.json" );

			Object transformedOutput = chainr.transform(inputJSON1);
			System.out.println("Tesstt :: "+JsonUtils.toJsonString(transformedOutput));

			logger.info("[JSONTransformationUtility] /transformJSON end: ");
		} catch (Exception e) {
			logger.debug("[JSONTransformationUtility] /transformJSON end: " + e.getMessage());
			e.printStackTrace();
		}

		return null;
	}
```
Output 👍 
```
[	{		"operation": "shift",		"spec": {			"file-info": {				"filename": "filename"			},			"main-text": {				"*": {					"text": "document"				}			},			"tables": {				"*": {					"data": "data&1"				}			},			"\\*": "\\&1.&"		}	},	{		"operation": "modify-overwrite-beta",		"spec": {			"document": "=join('',@(1,document))",			"data*": {				"*": "=join('',@(2,&1[&]))"			}		}	},	{				"operation": "modify-overwrite-beta",		"spec": {			"data*": "=join(' ',@(1,&))"		}	}]
2017-08-28 21:58:09.385 DEBUG 23136 --- [nio-8080-exec-1] .i.c.e.d.e.n.u.JSONTransformationUtility : [JSONTransformationUtility] /transformJSON end: JOLT Chainr could not find transform class:modify-overwrite-beta at index:1.
com.bazaarvoice.jolt.exception.SpecException: JOLT Chainr could not find transform class:modify-overwrite-beta at index:1.
	at com.bazaarvoice.jolt.chainr.spec.ChainrEntry.loadJoltTransformClass(ChainrEntry.java:142)
	at com.bazaarvoice.jolt.chainr.spec.ChainrEntry.<init>(ChainrEntry.java:95)
	at com.bazaarvoice.jolt.chainr.spec.ChainrSpec.<init>(ChainrSpec.java:68)
	at com.bazaarvoice.jolt.chainr.ChainrBuilder.<init>(ChainrBuilder.java:40)
	at com.bazaarvoice.jolt.Chainr.fromSpec(Chainr.java:92)
	at com.ibm.cdo.eci.data.extraction.nlu.utilities.JSONTransformationUtility.transformJSON(JSONTransformationUtility.java:73)
```
Would appreciate quick response.

**Comment by milosimpson** [comment]
Modify wasn't added till Jolt 0.0.22, you are using 0.0.20.      Jump up to the latest, if you can.

https://github.com/bazaarvoice/jolt/releases

**Comment by santooudnur** [comment]
Tried with v0.1.0 version , works fine. But should be documented with gradle in documentation. 

compile group: 'com.bazaarvoice.jolt', name: 'jolt-core', version: '0.1.0'
compile group: 'com.bazaarvoice.jolt', name: 'json-utils', version: '0.1.0'

**Comment by santooudnur** [comment]
Thanks a lot
