### ISSUE TITLE
JOLT CLI Error When Processing Array Of Anonymous Objects

### ISSUE THREAD

**Issue by hindmasj** [bazaarvoice/jolt#978]
I have an application that presents a list of records as anonymous JSON objects inside an array.

For example, a bit like this:-

````
[
  {
    "FirstSeenTime": 1589198358984942300,
    "LastSeenTime": 1589198358988729000,
    "RecordUUID": "5eb93e16-0060-4dd4-8353-8e010000029f",
    "SessionUUID": "5eb93e16-0060-4dd4-8353-8e010000029c",
    "MachineId": "102001"
  },
  {
    "FirstSeenTime": 1589198358987783000,
    "LastSeenTime": 1589198358989820000,
    "RecordUUID": "5eb93e16-0060-4dd4-8353-8e01000002a2",
    "SessionUUID": "5eb93e16-0060-4dd4-8353-8e010000029e",
    "MachineId": "102001"
  }
]
````
And I want to perform the same transform on each record, for example here I convert the nano second time to milliseconds, and the machine ID to an integer.

````
[
  {
    "operation": "modify-overwrite-beta",
    "spec": {
      "*": {
        "MachineId": ["=toInteger", 0],
        "FirstSeenTime": "=divideAndRound(0,@(1,FirstSeenTime),1000000)",
        "LastSeenTime": "=divideAndRound(0,@(1,LastSeenTime),1000000)"
      }
    }
  }
]
````

This works on the Jolt Transform Demo site, but if I use Jolt CLI I get this error

````
Failed to process standard input.
````

and by digging around in the code I find it is because of this stack trace

````
com.bazaarvoice.jolt.exception.JsonUnmarshalException: Unable to unmarshal JSON to a Map.
	at com.bazaarvoice.jolt.JsonUtilImpl.jsonToMap(JsonUtilImpl.java:132)
	at com.bazaarvoice.jolt.JsonUtils.jsonToMap(JsonUtils.java:129)
	at com.bazaarvoice.jolt.JoltCliUtilities.readJsonInput(JoltCliUtilities.java:100)
	at com.bazaarvoice.jolt.TransformCliProcessor.process(TransformCliProcessor.java:79)
	at com.bazaarvoice.jolt.JoltCli.runJolt(JoltCli.java:72)
	at com.bazaarvoice.jolt.JoltCli.main(JoltCli.java:42)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.LinkedHashMap` out of START_ARRAY token
 at [Source: (BufferedInputStream); line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1342)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1138)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1092)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromEmpty(StdDeserializer.java:599)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:360)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3065)
	at com.bazaarvoice.jolt.JsonUtilImpl.jsonToMap(JsonUtilImpl.java:129)
	... 5 more
````

I am using Jolt 0.1.2-SNAPSHOT, cloned from the master branch and built using Maven 3.6.3.

Is there a difference in the way Jolt CLI parses the input as opposed to how it is done on the Demo web site?

**Comment by hindmasj** [comment]
Retested under 0.1.9-SNAPSHOT and this works, so I can close this issue.
