### ISSUE TITLE
Custom operation with JOLT

### ISSUE THREAD

**Issue by msoni9** [bazaarvoice/jolt#982]
Hi @milosimpson 

Input Json : 
```
[
	{
	"f_name": "jack",
	"l_name": "jill",
	"email": "noreply@gmail.com",
	"date" : "11/15/2013"
},
{
	"f_name": "Tom",
	"l_name": "Hill",
	"email": "noreply1@gmail.com",
	"date" : "05/15/2013"
}
]
```
spec json :

```
[
	{
		"operation": "shift",
		"spec": {
			"f_name": "firstname",
			"l_name": "lastname",
			"email" : "email",
			"date" : "date"
		}
	},
	{
       "operation" : "com.mastercard.services.JsonCustomTransformer"
    }
]
```

expected output : 

```
[
	{
	"firstname": "jack",
	"lastname": "jill",
	"email": "noreply@gmail.com",
	"date" : "11-15-2013"
},
{
	"f_name": "Tom",
	"l_name": "Hill",
	"email": "noreply1@gmail.com",
	"date" : "05-15-2013"
}
]
```
Java code for Custom Jolt transform:

```
public class JsonCustomTransformer implements Transform {

	@Override
	public Object transform(Object input) {

		ObjectMapper mapper = new ObjectMapper();
		String json = null;
		Map map = null;
		try {
			json = mapper.writeValueAsString(input);
			map = mapper.readValue(json, Map.class);
		} catch (JsonProcessingException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}

		String dateFormat = (String) map.get("date");
		String previousString = (String) map.get("firstname");

		/**
		 * Todo logic - Change the value of first name
		 * 
		 */
		String newName = "geoff"; // Your custom date manipulation logic.

		/**
		 * Todo logic - Date format change
		 * 
		 */
		SimpleDateFormat in = new SimpleDateFormat("MM/dd/yyyy");
		Date inDate = null;
		try {
			inDate = in.parse(dateFormat);
		} catch (ParseException e) {
			e.printStackTrace();
		}
		SimpleDateFormat out = new SimpleDateFormat("MM-dd-yyyy");
		String newDate = out.format(inDate);

		/**
		 * insert it into map
		 */
		((Map) input).put("date", newDate);
		((Map) input).put("firstname", newName);

		/**
		 * return complete json object
		 */
		return input;

	}
}
```

Processing two Transforms here. One is shift and other is custom transform. Input json is in the form of List<Map>, and I'm processing this with java code and getting null pointer exception.

Here are the logs of Exception 

```
java.lang.NullPointerException: null
	at com.mastercard.services.JsonCustomTransformer.transform(JsonCustomTransformer.java:28) ~[classes/:na]
	at com.bazaarvoice.jolt.Chainr.doTransform(Chainr.java:229) ~[jolt-core-0.0.10.jar:0.1.0]
	at com.bazaarvoice.jolt.Chainr.transform(Chainr.java:164) ~[jolt-core-0.0.10.jar:0.1.0]
	at com.mastercard.services.JsonTransformer.toExpectedJson(JsonTransformer.java:24) ~[classes/:na]
	at com.mastercard.resource.EmployeeController.addEmployee(EmployeeController.java:33) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_172]
```

Your help will be appreciated.
Thanks in advance.

**Comment by msoni9** [comment]
I got the solution. Problem was with my spec json.

```
[
	{
		"operation": "shift",
		"spec": {
			"*": {
				"f_name": "[&1].firstname",
				"l_name": "[&1].lastname",
				"email": "[&1].email",
				"date": "[&1].date"
			}
		}
	},
	{
		"operation": "com.mastercard.services.JsonCustomTransformer"
	}
]
```
